FROM node:10 AS builder

WORKDIR /usr/src/app/
COPY . /usr/src/app/
RUN npm install
RUN npm run build
VOLUME /usr/src/app/

FROM node:10
WORKDIR /usr/src/app/
RUN npm install -g forever
COPY --from=builder /usr/src/app/build/ .
VOLUME /usr/src/app/
CMD forever start /usr/src/app/index.js
